language: ruby
rvm:
- 2.3.0
cache:
  bundler: true
before_install:
- gem update --system
- gem --version
- chmod +x ./_utils/*
- "./_utils/ci_generate.sh"
script:
- bundle exec jekyll build
- "./_utils/ci_prepare_deploy.sh"
after_success:
- "./_utils/ci_deploy.sh"
env:
  global:
  - JEKYLL_ENV=production
  - secure: FUGdgO4He66bk7lByolS93ZgI/F2oLQDo0uE1dAwdmwiaAwCaMUnu7kMSNq/tjQiJgY2GAqb1Z6mznuwYsLQYlnGbRS+y0E87L/4X/Wh0AlC6i9Hdh579/qLZ1kJXK14uL6iQioDdSRdoLMvsmnTEsZr2vsisLObtnun3lqyNAvLXSHRjggbox13104v3HObAYxTYkUu70Sbj6xunJg4PDfe1v8yPGrxMFmF2G5jusczVgDFE0/eXvxtWhM+RMHSdz/tItnGo0ywMmLYNjzb2gLuJ/JprdNFAWJrikWTD81QDre+rSGBA5Q9Jzbog1HjIjDKezJwPL6tZCYeorJnTVynogs4iGyxm3WTHRPtQckNleuVvo/+ucsim9RBC7nFhpo2TJwbar6326vFzPIIrc7mPed/Q/wu/lAyDTwuD5uZOyPGTE5tixnExj1DwHB3Ud3EvACZbA7wFmyvRU+XPaV3YksXxtCVFBm2wSUWYAll1zRD2YboQDb2uhrpP8nvoPSsKvTPL1WkHSgFErzYrOw/C22DfFlOSth0czXBVPgT7ar+4//LU/n3QiU909jUUTNfK5dciltGoL7J1ZTYXrHcTtth0jUj/XwU8KYpFsEOzNbvn+SAQnRcIP+ogAwHjQMikBsH2RFtuayBJqjAJMJmm0XZpj0289hOQI0Cukc=
  - secure: tWazkiFekTho62KqayphDwoj8FIuKAD+i+e4O6yFw8llhkOXFFs6YTiMaFYjSfOO7isgkrWCGMrdagGZCqozkBgsUrQVThhiayj8/zr1lYJiNB4a+ZlY8j3Nvhp2wNu17uIdaCM65VQk7oJeafsgc7amqiv2irXxqcxzvoPiucza4bioVStO9hUnbpWyHc2UOuV9eodfqGxfoehnlsyDgZaPhtQUy3hLJ6L5VUqV35kw0BSx9kGta8WzCKA8VCyriGNdpGNcg2+hx+bBgLdvjXuVFV4D3txxpvG857/OITH5NlX4+vBu8YaOoBJ0r9e7diAv6Kr0RxeMJNT9Zsbd0yLlmQ/M59+rwpxQeCDna+aY5wKRWFvLIY6JmNWO3et5XN1ipi2WmCgdMScptda8o4S9GimTWYbhbIUwUsvkGR357luKOnwhK9Tj794pKxUO7Hp76JE8RiSBl7y+treBf2Vvh89+AGWxXYshRffcM2wn6JgdGLUAHHw9OQoALFrI6gEpZtrE58A5J3IXNUzLB2+Ey+Yu7LaIpjyq+f3hFOUcOUSJ7ssMKybooJL1epUOWBYCKEck7QkOp/KPiSrKxY0cx8u/YUvf4uITULhjOlNtR3ORjP27F0umFgNE1KrzSV/OwvwtDmlPJwqRDzqllXo2TYj81lQ8BzjMu7XAk8Q=
  - ENCRYPTION_LABEL=dff9f3dc1b4c
  matrix:
  - BUILD_TARGET=QINIU
  - BUILD_TARGET=GITHUB_PAGES
notifications:
  slack:
    rooms:
      - secure: RQGKRURjyEmTKcJ/5trqS6EbBs3Zg68mBwYcv4e+j84D9ReGwDvnDCfiCOW2KAOz3WL+9to9LIVhp8AeKU6eKyOpZgD6OAnIAwlFHnjmb4wDTa54ShJFG+dVpUauXWeasPpNQj7TFG6IULw2isRwekwJcetBxxil/PWMFPbCsE17ug0xvJfC+T2RxiwK2HrgssrIntlVs8ZRSI+FZLtVQjMNN3UAz/8JJpPbc6nJ42JOETTa3x6EpYTa/BVLI6wACEo+QViWahVDcXEDwXmIWxRTFCM1TYQ7bMwNydAGTDGSoQRaMsTHGQBww35ssx5Q3S8hsl9SjaN8C0PAdN8mMd6b0UgpQ7lVHb5tMXLyLDoGXbS3bglDqi9diMMo46LPWSoe+L+VNbr4lYLmEw1Cq+qyyNOJTwFBZXih9hra/SiqX15CKtZyAB+uNSt1MgHDEs3HQ6g+DQWxHXLKFit3yWduFEwSTD8lrwrvach0mC0S/6pn89nrKN5x/8OEaEJpSqrT3B0zZ+uPIGAWfthvcIkktnu/O/d/O1MtHZWL5CFW/uKIajgDZx1DMQ0yUtUejZgBqyGoP4zEX/A4yfXkTBZQxaZ97pJqy/jdoLAv5n59wVcBzFnapFpo+MBXVJXFods/gwtx/5yo4dJ+TxlZ1pZB6EwatxijyBAK1oQ0iIs=
      - secure: iG5ixQqlQJ7sHUNXHxbuf3M0ZF8lZ/wSGPwoFVlWBMgWMsZ5jZwNxsYBY19WRDRqOJNRXfiNpnQBAfUuC0IEs+CvQMa4180tggBD/ZpRIOtYDBfSjqkqbmtPlKK6vdid4WIwOQ0WiNAiu3lYwcolLVNilHQKqR4WlBYE8QUM1/JBdiNG22rph8MqHqTqIxC5LGDRBDEuMRFVdHPr+QOQbE6SRA+bAeMnmfUghnOGF5IXIih0obDaXHDt5gjGLgtmogfH4XlL/wJuIZpPdp3Tcd4XRWIaUamqYMzduaGwPBXx5GYdcboh28/HJt65C2a1uvVAmWQTvhX/GPR2vWQ++hTBk/pmsAWmA2/gdp+Ci9sSouML/sb1G98wXzCqz4buEZPNq3Q45k4CttXx0pCCcFOWMqU0sF8Z1/+KIn++O03F7XW6THA1bJQbTxMKvJhFtwsY4FJoVnjHqebBPLUVscNF7i4qIzwssFXol2vZd89EymQbP6oVH73YnCJ/A8kOW5QhEglswnw2ZEHKSczwxI4mkAU9rpK/LNuW2K/LRybzwIZyLZLL0Qqw+dqrLJFHZel6a9tgUj/F9AFuK7B6GROcXknRrS1kw4sD11Aa/J+kemgFDdXQ3s4hyWvGcaJm+Hes3aNkY42I+rZhpCqyaWseLR/UbSBk1S4i0hjMbNs=
addons:
  apt:
    packages:
    - gettext
