language: ruby
rvm:
- 2.2.2
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y gettext
- gem update --system
- gem --version
- chmod +x ./_utils/*
- "./_utils/ci_generate.sh"
script:
- jekyll build
- "./_utils/ci_deploy.sh"
env:
  global:
  - JEKYLL_ENV=production
  - secure: FUGdgO4He66bk7lByolS93ZgI/F2oLQDo0uE1dAwdmwiaAwCaMUnu7kMSNq/tjQiJgY2GAqb1Z6mznuwYsLQYlnGbRS+y0E87L/4X/Wh0AlC6i9Hdh579/qLZ1kJXK14uL6iQioDdSRdoLMvsmnTEsZr2vsisLObtnun3lqyNAvLXSHRjggbox13104v3HObAYxTYkUu70Sbj6xunJg4PDfe1v8yPGrxMFmF2G5jusczVgDFE0/eXvxtWhM+RMHSdz/tItnGo0ywMmLYNjzb2gLuJ/JprdNFAWJrikWTD81QDre+rSGBA5Q9Jzbog1HjIjDKezJwPL6tZCYeorJnTVynogs4iGyxm3WTHRPtQckNleuVvo/+ucsim9RBC7nFhpo2TJwbar6326vFzPIIrc7mPed/Q/wu/lAyDTwuD5uZOyPGTE5tixnExj1DwHB3Ud3EvACZbA7wFmyvRU+XPaV3YksXxtCVFBm2wSUWYAll1zRD2YboQDb2uhrpP8nvoPSsKvTPL1WkHSgFErzYrOw/C22DfFlOSth0czXBVPgT7ar+4//LU/n3QiU909jUUTNfK5dciltGoL7J1ZTYXrHcTtth0jUj/XwU8KYpFsEOzNbvn+SAQnRcIP+ogAwHjQMikBsH2RFtuayBJqjAJMJmm0XZpj0289hOQI0Cukc=
  - secure: tWazkiFekTho62KqayphDwoj8FIuKAD+i+e4O6yFw8llhkOXFFs6YTiMaFYjSfOO7isgkrWCGMrdagGZCqozkBgsUrQVThhiayj8/zr1lYJiNB4a+ZlY8j3Nvhp2wNu17uIdaCM65VQk7oJeafsgc7amqiv2irXxqcxzvoPiucza4bioVStO9hUnbpWyHc2UOuV9eodfqGxfoehnlsyDgZaPhtQUy3hLJ6L5VUqV35kw0BSx9kGta8WzCKA8VCyriGNdpGNcg2+hx+bBgLdvjXuVFV4D3txxpvG857/OITH5NlX4+vBu8YaOoBJ0r9e7diAv6Kr0RxeMJNT9Zsbd0yLlmQ/M59+rwpxQeCDna+aY5wKRWFvLIY6JmNWO3et5XN1ipi2WmCgdMScptda8o4S9GimTWYbhbIUwUsvkGR357luKOnwhK9Tj794pKxUO7Hp76JE8RiSBl7y+treBf2Vvh89+AGWxXYshRffcM2wn6JgdGLUAHHw9OQoALFrI6gEpZtrE58A5J3IXNUzLB2+Ey+Yu7LaIpjyq+f3hFOUcOUSJ7ssMKybooJL1epUOWBYCKEck7QkOp/KPiSrKxY0cx8u/YUvf4uITULhjOlNtR3ORjP27F0umFgNE1KrzSV/OwvwtDmlPJwqRDzqllXo2TYj81lQ8BzjMu7XAk8Q=
  - ENCRYPTION_LABEL: dff9f3dc1b4c
  - COMMIT_AUTHOR_EMAIL: SkyZH@users.noreply.github.com
  matrix:
    - BUILD_TARGET=GITHUB_PAGES
    - BUILD_TARGET=QINIU
exclude:
- vendor
notifications:
  slack:
    rooms:
    - secure: l7IuBBQUmj5BsQWw01oZYjat2Vvl2YJMilFf814qR7UyzS5FSXdvv00W/aAuD1cozRtXWX/71zhPG48ADrXsDSd8LORefgxpq9V/rVDOMGb+v+IE6BcUZmuHBBrRNtlxP/T9UteGhh+mkKLS7r56Iy7RVbLvL3l+Ytn1h9fy13zIv03Ln4FzugZIeB40Tsi/+syBtwuObWcxszPHHk29yHco7UjAM2Wq8veMV1cpa/5VdVCyoPSop3bd3jsJ4Fl6qHwz2+4lRJBRjUGDzwQdoHZwqkxsqFYSmLMex+WYfhgVpe95ED7OsAchVwpmGvsR/yGp7is6we3LJabFw31FVfUCcUf6Z6z9n36DNqD8JjlQMgqDbcKNKkDseKnKqV2Nmc65+fwmYU2QkSOUhbUNlAG486EwuNKxw6UAL1ZKHnLCZZRjNo3gtk3Aq9jWGrDwfiE5d/qaCqpKFhIc9Eg3IxmEpn1NqsepKVC6e1nANT4fyaQzYsyRyBjEKPRumnZ0aPRMyH4ryINiLgY89OH8JqWRWYaJAdWpVXipgoQDWfElr5JK+n5q2QGy+LA02cm2/9xFBzEaIY8NtsROSgcT/+Xxaa2Mrjyuj0nAFKkiTYfh1KzohsPegF4Tnme73ZsJTtzUsDxv0x2t5HbCeOcaL/ppkPXTOmqXHbja+ntvoFc=
    - secure: oTF/QHgMo0Fa1I2JLVny6CK1Ug47wosBnKoREmUinuLhhJWz60tiNLKdgi3hjJN7NKyaBOwQveyk2msGzY/4NQzhhC/1yJCTTUSOAtD9ccRdYmux6kXNtriuc/5NcTQJpUBKzMQQM+l1FHwTEEWJaTF2qh4xKPb635HFiDyxaRMY0DH8XaRrWP4ur0LzYYWyge+1ce46HlzdDXByOTrNlX7adYS9YZr35niZ93KuQXHfRrF1kGzcpYT6xzSvikRxRk6a57RZPpLOTK9luBIfyIDDpjbwBm8RaEDr1rPs+YSiB3o9pVMS11j83pPnqKUnvCCYPelNBe2K3RdeF8eI8LPG6n97HJyNHD3iXjVZ1cKNOqv9Gk2vcjjNd7IGnd5UssdEBRJIRGW4fBh8AfCqLGp9y9gL3iTCa8SHQqABs7Dni8YuxPEaV4BwEJ7AqT12lg9H1zQdAj4BCy1Bk+/1UFnBhWgJqT3zMmSVe25+ursRHDwKl04XeaEQVk/IXVksMYu0EG/aD2fwSJDGiuDYtH3/fg3NWLE//QpLuvwigwxXPwx7qx2It83272HD83cMPCY+bNm8WWe4Gte5mXpzbFVmQHGXT2p11TbAyhgjqBH2fcE3DOTYIM8x28HrsGhBxk7LNmqETKZv78e0e5fkT/nSQIkM/tLoGNSFE1AktUQ=
