# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Team 9036 | Zodiac
email:
description: ZODIAC
baseurl: ""
url: "http://frc.hsefz.org"

# Build settings
markdown: kramdown

gems:
  - jekyll-assets

assets:
  compress:
    css: true
    js: true

  #

  autowrite: true
  cdn: http://frc.hsefz.org
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true

  #

  sources:
    - _assets/css
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/img
    - _assets/js

  digest: true
